// tech-news-agent scenarios — design §7.3
// Values: threshold 0.6, example confidence 0.83, fact count 6, ~63 s runtime, markers [HIGH]/[MEDIUM]/[UNVERIFIED]
import type { Scenario } from "../engine/types";

export const agentsScenarios: Scenario[] = [
  {
    id: "run-pipeline",
    label: "Run pipeline",
    narration: [
      "Topic 'NVIDIA Blackwell GPU' sent to OrchestratorAgent",
      "Orchestrator runs ReAct loop: reason → act → observe",
      "ScoutAgent calls Tavily and GitHub MCP to gather facts",
      "6 facts collected; ReporterAgent generates article draft",
      "EditorAgent refines the article",
      "FactCheckerAgent runs; confidence 0.83 — passes threshold 0.6",
      "LinkedInWriterAgent formats the post",
      "Output card: [HIGH], [MEDIUM], [UNVERIFIED] markers — example response, ~63 s",
    ],
    steps: [
      { t: 0,    kind: "set",    target: "topic.text",    value: "NVIDIA Blackwell GPU" },
      { t: 0,    kind: "packet", edge: "e-topic-orchestrator", label: "topic",     tone: "signal", duration: 700 },
      { t: 700,  kind: "pulse",  node: "orchestrator",    tone: "signal" },
      { t: 700,  kind: "say",    text: "Topic received; Orchestrator running ReAct loop" },
      { t: 1000, kind: "packet", edge: "e-orchestrator-scout", label: "dispatch", tone: "signal", duration: 600 },
      { t: 1600, kind: "pulse",  node: "scout",           tone: "signal" },
      { t: 1800, kind: "packet", edge: "e-scout-tavily",  label: "search",        tone: "signal", duration: 500 },
      { t: 1800, kind: "packet", edge: "e-scout-github",  label: "data",          tone: "signal", duration: 500 },
      { t: 2400, kind: "set",    target: "facts",         value: 6 },
      { t: 2400, kind: "say",    text: "ScoutAgent gathered 6 facts via Tavily and GitHub MCP" },
      { t: 2600, kind: "packet", edge: "e-scout-reporter",label: "facts:6",       tone: "signal", duration: 600 },
      { t: 3200, kind: "pulse",  node: "reporter",        tone: "signal" },
      { t: 3500, kind: "packet", edge: "e-reporter-editor",label: "draft",        tone: "signal", duration: 600 },
      { t: 4100, kind: "pulse",  node: "editor",          tone: "signal" },
      { t: 4400, kind: "packet", edge: "e-editor-factcheck",label: "article",     tone: "signal", duration: 600 },
      { t: 5000, kind: "pulse",  node: "factcheck",       tone: "signal" },
      { t: 5000, kind: "set",    target: "gauge.value",   value: 0.83 },
      { t: 5000, kind: "say",    text: "Fact check passed with confidence 0.83" },
      { t: 5500, kind: "packet", edge: "e-factcheck-linkedin",label: "verified",  tone: "signal", duration: 600 },
      { t: 6100, kind: "pulse",  node: "linkedin",        tone: "signal" },
      { t: 6400, kind: "packet", edge: "e-linkedin-output",label: "post",         tone: "signal", duration: 600 },
      { t: 7000, kind: "set",    target: "output.markers", value: "[HIGH] [MEDIUM] [UNVERIFIED]" },
      { t: 7000, kind: "set",    target: "output.caption", value: "example response, ~63 s" },
      { t: 7000, kind: "say",    text: "Post ready: [HIGH], [MEDIUM], [UNVERIFIED] markers — example response, ~63 s" },
    ],
  },
  {
    id: "force-retry",
    label: "Force a retry",
    narration: [
      "Same pipeline runs; FactChecker confidence 0.52 — below threshold 0.6",
      "Retry decided by the model, not hardcoded Java",
      "FactChecker sends re-extract request to Reporter",
      "Second pass: confidence 0.83 — passes; pipeline continues",
      "Output card with [HIGH], [MEDIUM], [UNVERIFIED] markers",
    ],
    steps: [
      { t: 0,    kind: "set",    target: "topic.text",    value: "NVIDIA Blackwell GPU" },
      { t: 0,    kind: "packet", edge: "e-topic-orchestrator", label: "topic",    tone: "signal", duration: 700 },
      { t: 700,  kind: "pulse",  node: "orchestrator",    tone: "signal" },
      { t: 1000, kind: "packet", edge: "e-orchestrator-scout", label: "dispatch", tone: "signal", duration: 600 },
      { t: 1600, kind: "pulse",  node: "scout",           tone: "signal" },
      { t: 1800, kind: "packet", edge: "e-scout-tavily",  label: "search",       tone: "signal", duration: 500 },
      { t: 2400, kind: "set",    target: "facts",         value: 6 },
      { t: 2600, kind: "packet", edge: "e-scout-reporter",label: "facts:6",      tone: "signal", duration: 600 },
      { t: 3200, kind: "pulse",  node: "reporter",        tone: "signal" },
      { t: 3500, kind: "packet", edge: "e-reporter-editor",label: "draft",       tone: "signal", duration: 600 },
      { t: 4100, kind: "pulse",  node: "editor",          tone: "signal" },
      { t: 4400, kind: "packet", edge: "e-editor-factcheck",label: "article",    tone: "signal", duration: 600 },
      // First fact check — FAILS (0.52, illustrative — labeled on screen)
      { t: 5000, kind: "pulse",  node: "factcheck",       tone: "fault" },
      { t: 5000, kind: "set",    target: "gauge.value",   value: 0.52 },
      { t: 5000, kind: "set",    target: "gauge.caption", value: "retry (illustrative)" },
      { t: 5000, kind: "say",    text: "Fact check confidence 0.52 — below threshold 0.6; retry" },
      // Loop back
      { t: 5600, kind: "packet", edge: "e-factcheck-reporter",label:"re-extract", tone: "fault", duration: 700 },
      { t: 6300, kind: "pulse",  node: "orchestrator",    tone: "signal" },
      // Second pass
      { t: 6600, kind: "packet", edge: "e-reporter-editor",label: "draft v2",   tone: "signal", duration: 600 },
      { t: 7200, kind: "packet", edge: "e-editor-factcheck",label: "article v2", tone: "signal", duration: 600 },
      { t: 7800, kind: "pulse",  node: "factcheck",       tone: "signal" },
      { t: 7800, kind: "set",    target: "gauge.value",   value: 0.83 },
      { t: 7800, kind: "set",    target: "gauge.caption", value: "" },
      { t: 7800, kind: "say",    text: "Second pass: confidence 0.83 — passed" },
      { t: 8200, kind: "packet", edge: "e-factcheck-linkedin",label: "verified", tone: "signal", duration: 600 },
      { t: 8800, kind: "packet", edge: "e-linkedin-output",label: "post",        tone: "signal", duration: 600 },
      { t: 9400, kind: "set",    target: "output.markers", value: "[HIGH] [MEDIUM] [UNVERIFIED]" },
      { t: 9400, kind: "set",    target: "output.caption", value: "example response, ~63 s" },
      { t: 9400, kind: "say",    text: "Post ready with markers after retry" },
    ],
  },
];
