// Salon Appointment System scenarios.
// Every status, frame and value traces to the project README:
// seven-state machine, the GiST exclusion constraint, SQLSTATE 23P01 → SLOT_CONFLICT,
// and the reschedule-by-replacement-row design.
import type { Scenario } from "../engine/types";

export const salonScenarios: Scenario[] = [
  {
    id: "book-appointment",
    label: "Book an appointment",
    narration: [
      "Customer submits a booking; the phone number is read from the verified-phone cookie, never from the request body",
      "Appointment inserted and flushed; the exclusion constraint accepts it",
      "Appointment status is REQUESTED — a booking is a request, not a confirmation",
      "The assigned stylist is notified; approval is a human decision",
      "Stylist approves; status moves to CONFIRMED",
      "Confirmation sent with a signed manage link the customer can use without logging in",
    ],
    steps: [
      { t: 0, kind: "packet", edge: "e-A-api", label: "POST /api/booking", tone: "signal", duration: 700 },
      { t: 700, kind: "pulse", node: "api", tone: "signal" },
      { t: 700, kind: "say", text: "Booking submitted; phone taken from the verified-phone cookie only" },
      { t: 1000, kind: "packet", edge: "e-api-pg", label: "INSERT + FLUSH", tone: "signal", duration: 700 },
      { t: 1700, kind: "pulse", node: "postgres", tone: "signal" },
      { t: 1700, kind: "status", node: "postgres", value: "REQUESTED", tone: "idle" },
      { t: 1700, kind: "say", text: "Exclusion constraint accepted the insert; appointment is REQUESTED" },
      { t: 2100, kind: "packet", edge: "e-api-sms", label: "notify stylist", tone: "signal", duration: 600 },
      { t: 2700, kind: "packet", edge: "e-sms-stylist", label: "new request", tone: "signal", duration: 600 },
      { t: 3300, kind: "pulse", node: "stylist", tone: "signal" },
      { t: 3300, kind: "say", text: "Assigned stylist notified — only they may approve or decline" },
      { t: 3900, kind: "packet", edge: "e-stylist-api", label: "approve", tone: "signal", duration: 700 },
      { t: 4600, kind: "status", node: "postgres", value: "CONFIRMED", tone: "signal" },
      { t: 4600, kind: "pulse", node: "postgres", tone: "signal" },
      { t: 4600, kind: "say", text: "Approved; status CONFIRMED and reminders scheduled" },
      { t: 5000, kind: "packet", edge: "e-api-sms", label: "confirmation", tone: "signal", duration: 600 },
      { t: 5400, kind: "packet", edge: "e-api-A", label: "manage link", tone: "signal", duration: 700 },
      { t: 6100, kind: "say", text: "Confirmation sent with a signed manage link — no login needed to cancel or reschedule" },
    ],
  },
  {
    id: "slot-conflict",
    label: "Two customers, one slot",
    narration: [
      "Two customers submit a booking for the same slot within milliseconds",
      "Both pass the service-layer availability check — neither request has committed when the other checks",
      "Customer A's insert is accepted by the exclusion constraint",
      "Customer B's insert reaches the same constraint and is rejected",
      "SQLSTATE 23P01 is translated narrowly to 409 SLOT_CONFLICT; only A holds the slot",
    ],
    steps: [
      { t: 0, kind: "packet", edge: "e-A-api", label: "POST /api/booking", tone: "signal", duration: 700 },
      { t: 100, kind: "packet", edge: "e-B-api", label: "POST /api/booking", tone: "signal", duration: 700 },
      { t: 800, kind: "pulse", node: "api", tone: "signal" },
      { t: 800, kind: "say", text: "Both requests pass the availability check — it is advisory, not a guarantee" },
      { t: 1200, kind: "packet", edge: "e-api-pg", label: "INSERT A", tone: "signal", duration: 600 },
      { t: 1800, kind: "pulse", node: "postgres", tone: "signal" },
      { t: 1800, kind: "status", node: "postgres", value: "REQUESTED", tone: "idle" },
      { t: 1800, kind: "say", text: "Customer A's insert is accepted and locks the range" },
      { t: 2300, kind: "packet", edge: "e-api-pg", label: "INSERT B", tone: "fault", duration: 600 },
      { t: 2900, kind: "pulse", node: "postgres", tone: "fault" },
      { t: 2900, kind: "say", text: "Customer B's insert reaches the exclusion constraint" },
      { t: 3300, kind: "packet", edge: "e-pg-api", label: "23P01", tone: "fault", duration: 700 },
      { t: 4000, kind: "pulse", node: "api", tone: "fault" },
      { t: 4000, kind: "set", target: "conflict", value: "409 SLOT_CONFLICT" },
      { t: 4000, kind: "say", text: "Exclusion constraint rejected the second insert: 409 SLOT_CONFLICT" },
      { t: 4500, kind: "status", node: "postgres", value: "REQUESTED", tone: "signal" },
      { t: 4500, kind: "say", text: "Only customer A holds the slot; the database was the arbiter, not the application" },
    ],
  },
  {
    id: "reschedule",
    label: "Reschedule",
    narration: [
      "An appointment is already CONFIRMED and holding its slot",
      "The customer opens the signed manage link and asks for a new time",
      "A new request row is inserted pointing at the original — the original is not touched",
      "The original stays CONFIRMED and keeps holding its slot while the replacement waits",
      "The stylist approves the replacement; the original is cancelled silently",
      "If nobody approves, the replacement expires and the original booking still stands",
    ],
    steps: [
      { t: 0, kind: "status", node: "postgres", value: "CONFIRMED", tone: "signal" },
      { t: 0, kind: "say", text: "Original appointment is CONFIRMED and holding its slot" },
      { t: 500, kind: "packet", edge: "e-A-api", label: "POST /manage/{token}/reschedule", tone: "signal", duration: 800 },
      { t: 1300, kind: "pulse", node: "api", tone: "signal" },
      { t: 1300, kind: "say", text: "Signed manage link verified; no login required" },
      { t: 1700, kind: "packet", edge: "e-api-pg", label: "INSERT replacement", tone: "signal", duration: 700 },
      { t: 2400, kind: "pulse", node: "postgres", tone: "signal" },
      { t: 2400, kind: "set", target: "replaces", value: "replaces_appointment_id → original" },
      { t: 2400, kind: "say", text: "New REQUESTED row points at the original; the original is untouched and still holds its slot" },
      { t: 2900, kind: "packet", edge: "e-api-sms", label: "notify stylist", tone: "signal", duration: 600 },
      { t: 3500, kind: "packet", edge: "e-sms-stylist", label: "new request", tone: "signal", duration: 600 },
      { t: 4100, kind: "pulse", node: "stylist", tone: "signal" },
      { t: 4500, kind: "packet", edge: "e-stylist-api", label: "approve", tone: "signal", duration: 700 },
      { t: 5200, kind: "status", node: "postgres", value: "CONFIRMED", tone: "signal" },
      { t: 5200, kind: "set", target: "replaces", value: "original → CANCELLED" },
      { t: 5200, kind: "say", text: "Replacement CONFIRMED; the original is cancelled silently in the same operation" },
      { t: 5700, kind: "packet", edge: "e-api-A", label: "new manage link", tone: "signal", duration: 700 },
      { t: 6400, kind: "say", text: "The customer can never end up with no appointment by trying to move one" },
    ],
  },
];
