// Order-Saga scenarios — step tables from design §7.1
// Every node, topic, and state traces to the README.
import type { Scenario } from "../engine/types";

export const orderSagaScenarios: Scenario[] = [
  {
    id: "place-order",
    label: "Place order",
    narration: [
      "POST /api/orders received by Gateway; forwarded to Order service",
      "Order created with status PENDING",
      "order.created event published to Kafka; Inventory consumes it",
      "Inventory reserves stock; inventory.reserved published",
      "Order status → INVENTORY_RESERVED; Payment consumes event",
      "Payment calls mock payment gateway",
      "payment.succeeded published; Order and Shipping consume it",
      "Order status → PAYMENT_PROCESSING; Shipping processes shipment",
      "shipment.created published; Order and Notification consume it",
      "Order status → COMPLETED; notification sent",
    ],
    steps: [
      { t: 0,    kind: "packet", edge: "e-gw-order",       label: "POST /api/orders",    tone: "signal", duration: 700 },
      { t: 700,  kind: "status", node: "order",             value: "PENDING",             tone: "idle" },
      { t: 700,  kind: "say",    text: "Order created, status PENDING" },
      { t: 900,  kind: "packet", edge: "e-order-kafka",     label: "order.created",       tone: "signal", duration: 600 },
      { t: 900,  kind: "packet", edge: "e-kafka-inventory", label: "order.created",       tone: "signal", duration: 600 },
      { t: 1900, kind: "pulse",  node: "inventory",         tone: "signal" },
      { t: 1900, kind: "set",    target: "inventory.processed", value: 1 },
      { t: 2100, kind: "packet", edge: "e-inventory-kafka", label: "inventory.reserved",  tone: "signal", duration: 700 },
      { t: 2100, kind: "packet", edge: "e-kafka-payment",   label: "inventory.reserved",  tone: "signal", duration: 700 },
      { t: 3100, kind: "status", node: "order",             value: "INVENTORY_RESERVED",  tone: "signal" },
      { t: 3100, kind: "pulse",  node: "payment",           tone: "signal" },
      { t: 3400, kind: "packet", edge: "e-payment-kafka",   label: "payment gateway",     tone: "signal", duration: 600 },
      { t: 4200, kind: "packet", edge: "e-payment-kafka",   label: "payment.succeeded",   tone: "signal", duration: 700 },
      { t: 4200, kind: "packet", edge: "e-kafka-shipping",  label: "payment.succeeded",   tone: "signal", duration: 700 },
      { t: 5200, kind: "status", node: "order",             value: "PAYMENT_PROCESSING",  tone: "signal" },
      { t: 5200, kind: "pulse",  node: "shipping",          tone: "signal" },
      { t: 5500, kind: "packet", edge: "e-shipping-kafka",  label: "shipment.created",    tone: "signal", duration: 700 },
      { t: 5500, kind: "packet", edge: "e-kafka-notification",label: "shipment.created",  tone: "signal", duration: 700 },
      { t: 6500, kind: "status", node: "order",             value: "COMPLETED",           tone: "signal" },
      { t: 6500, kind: "pulse",  node: "notification",      tone: "signal" },
      { t: 6500, kind: "say",    text: "Shipment created, order COMPLETED, notification sent" },
    ],
  },
  {
    id: "fail-payment",
    label: "Fail payment",
    narration: [
      "Order created, status PENDING; order.created published",
      "Inventory reserves stock; inventory.reserved published",
      "Order → INVENTORY_RESERVED; Payment processes",
      "Payment gateway fails; payment.failed published to Inventory, Order, Notification",
      "Order → COMPENSATING; Inventory releases reserved stock",
      "Order → FAILED; failure email sent",
    ],
    steps: [
      { t: 0,    kind: "packet", edge: "e-gw-order",       label: "POST /api/orders",    tone: "signal", duration: 700 },
      { t: 700,  kind: "status", node: "order",             value: "PENDING",             tone: "idle" },
      { t: 900,  kind: "packet", edge: "e-order-kafka",     label: "order.created",       tone: "signal", duration: 600 },
      { t: 900,  kind: "packet", edge: "e-kafka-inventory", label: "order.created",       tone: "signal", duration: 600 },
      { t: 1900, kind: "pulse",  node: "inventory",         tone: "signal" },
      { t: 2100, kind: "packet", edge: "e-inventory-kafka", label: "inventory.reserved",  tone: "signal", duration: 700 },
      { t: 2100, kind: "packet", edge: "e-kafka-payment",   label: "inventory.reserved",  tone: "signal", duration: 700 },
      { t: 3100, kind: "status", node: "order",             value: "INVENTORY_RESERVED",  tone: "signal" },
      { t: 3100, kind: "pulse",  node: "payment",           tone: "signal" },
      { t: 3400, kind: "packet", edge: "e-payment-kafka",   label: "payment gateway",     tone: "signal", duration: 600 },
      // Payment fails
      { t: 4200, kind: "packet", edge: "e-kafka-inventory", label: "payment.failed",      tone: "fault",  duration: 700 },
      { t: 4200, kind: "packet", edge: "e-kafka-notification",label:"payment.failed",     tone: "fault",  duration: 700 },
      { t: 4200, kind: "packet", edge: "e-order-kafka",     label: "payment.failed",      tone: "fault",  duration: 700 },
      { t: 5000, kind: "status", node: "order",             value: "COMPENSATING",        tone: "fault" },
      { t: 5000, kind: "pulse",  node: "inventory",         tone: "fault" },
      { t: 5000, kind: "set",    target: "inventory.stock", value: "released" },
      { t: 5500, kind: "status", node: "order",             value: "FAILED",              tone: "fault" },
      { t: 5500, kind: "say",    text: "Payment failed; inventory released; order FAILED; failure email sent" },
    ],
  },
  {
    id: "out-of-stock",
    label: "Out of stock",
    narration: [
      "Order created, status PENDING; order.created published",
      "Inventory unavailable; inventory.failed published to Order and Notification",
      "Order → FAILED; out-of-stock email sent",
    ],
    steps: [
      { t: 0,    kind: "packet", edge: "e-gw-order",       label: "POST /api/orders",    tone: "signal", duration: 700 },
      { t: 700,  kind: "status", node: "order",             value: "PENDING",             tone: "idle" },
      { t: 900,  kind: "packet", edge: "e-order-kafka",     label: "order.created",       tone: "signal", duration: 600 },
      { t: 900,  kind: "packet", edge: "e-kafka-inventory", label: "order.created",       tone: "signal", duration: 600 },
      { t: 1900, kind: "pulse",  node: "inventory",         tone: "fault" },
      { t: 2100, kind: "packet", edge: "e-inventory-kafka", label: "inventory.failed",    tone: "fault",  duration: 700 },
      { t: 2100, kind: "packet", edge: "e-kafka-notification",label:"inventory.failed",   tone: "fault",  duration: 700 },
      { t: 3000, kind: "status", node: "order",             value: "FAILED",              tone: "fault" },
      { t: 3000, kind: "say",    text: "Inventory unavailable; order FAILED; out-of-stock email sent" },
    ],
  },
];
