// rag-document-qa scenarios — from design §7.2
// Values: 500/50 chunking, top-k 5, example question from README.
import type { Scenario } from "../engine/types";

export const ragScenarios: Scenario[] = [
  {
    id: "ingest-document",
    label: "Ingest a document",
    narration: [
      "Upload accepted — 202, processing in the background",
      "PDFBox extracts digital text from the PDF",
      "Page split into 8 chunks (500 tokens, 50-token overlap)",
      "Chunks embedded with text-embedding-3-small (1536 dimensions)",
      "Vectors stored in PostgreSQL + pgvector (ivfflat index); document READY",
    ],
    steps: [
      { t: 0,    kind: "packet", edge: "e-upload-extract", label: "upload",       tone: "signal", duration: 600 },
      { t: 600,  kind: "status", node: "upload",           value: "PROCESSING",   tone: "idle" },
      { t: 600,  kind: "say",    text: "Upload accepted, 202, processing in the background" },
      { t: 800,  kind: "pulse",  node: "extract",          tone: "signal" },
      { t: 800,  kind: "say",    text: "PDFBox extracting digital text" },
      { t: 1400, kind: "packet", edge: "e-extract-chunk",  label: "text",         tone: "signal", duration: 600 },
      { t: 2000, kind: "pulse",  node: "chunk",            tone: "signal" },
      { t: 2000, kind: "set",    target: "chunk.caption",  value: "500 tokens, 50 overlap" },
      { t: 2200, kind: "packet", edge: "e-chunk-embed",    label: "8 chunks",     tone: "signal", duration: 700 },
      { t: 2900, kind: "pulse",  node: "embed",            tone: "signal" },
      { t: 3200, kind: "packet", edge: "e-embed-store",    label: "vectors",      tone: "signal", duration: 700 },
      { t: 3200, kind: "packet", edge: "e-store-vectors",  label: "8 dots",       tone: "signal", duration: 500 },
      { t: 4000, kind: "pulse",  node: "store",            tone: "signal" },
      { t: 4000, kind: "status", node: "upload",           value: "READY",        tone: "signal" },
      { t: 4000, kind: "set",    target: "chunks",         value: 8 },
      { t: 4000, kind: "say",    text: "Chunks embedded and stored, document READY" },
    ],
  },
  {
    id: "ingest-scanned",
    label: "Ingest a scanned page",
    narration: [
      "Upload accepted — 202, processing in the background",
      "PDFBox finds too little digital text — falls through",
      "Tesseract OCR fallback produces the page text",
      "Chunks embedded and stored; document READY",
    ],
    steps: [
      { t: 0,    kind: "packet", edge: "e-upload-extract", label: "upload",       tone: "signal", duration: 600 },
      { t: 600,  kind: "status", node: "upload",           value: "PROCESSING",   tone: "idle" },
      { t: 600,  kind: "say",    text: "Upload accepted, 202, processing in background" },
      // PDFBox lights then dims (falls through)
      { t: 900,  kind: "pulse",  node: "extract",          tone: "fault" },
      { t: 900,  kind: "set",    target: "extract.strategy", value: "PDFBox → ✗" },
      { t: 900,  kind: "say",    text: "Digital text too short; OCR fallback produced the page text" },
      // Tesseract lights
      { t: 1600, kind: "pulse",  node: "extract",          tone: "signal" },
      { t: 1600, kind: "set",    target: "extract.strategy", value: "Tesseract ✓" },
      { t: 2200, kind: "packet", edge: "e-extract-chunk",  label: "text",         tone: "signal", duration: 600 },
      { t: 2800, kind: "pulse",  node: "chunk",            tone: "signal" },
      { t: 3100, kind: "packet", edge: "e-chunk-embed",    label: "chunks",       tone: "signal", duration: 700 },
      { t: 3800, kind: "packet", edge: "e-embed-store",    label: "vectors",      tone: "signal", duration: 700 },
      { t: 3800, kind: "packet", edge: "e-store-vectors",  label: "dots",         tone: "signal", duration: 500 },
      { t: 4500, kind: "status", node: "upload",           value: "READY",        tone: "signal" },
      { t: 4500, kind: "say",    text: "Chunks embedded and stored, document READY" },
    ],
  },
  {
    id: "ask-question",
    label: "Ask a question",
    narration: [
      "Question: 'What are the payment terms?' embedded with text-embedding-3-small",
      "Top-5 nearest chunks retrieved from pgvector (cosine similarity)",
      "5 chunks assembled into prompt",
      "Answer streamed token by token via Server-Sent Events",
      "Source citations appended: Chunk 12 (page 4), Chunk 7 (page 2)",
      "Confidence 0.87 (example from the README)",
    ],
    steps: [
      { t: 0,    kind: "set",    target: "question.text",  value: "What are the payment terms?" },
      { t: 0,    kind: "pulse",  node: "question",         tone: "signal" },
      { t: 400,  kind: "packet", edge: "e-question-vectors",label: "embed",       tone: "signal", duration: 700 },
      { t: 1100, kind: "pulse",  node: "vectors",          tone: "signal" },
      { t: 1100, kind: "set",    target: "vectors.topk",   value: "top-k 5" },
      { t: 1100, kind: "say",    text: "Question embedded; five nearest chunks retrieved" },
      { t: 1500, kind: "packet", edge: "e-vectors-prompt", label: "5 chunks",    tone: "signal", duration: 700 },
      { t: 2200, kind: "pulse",  node: "prompt",           tone: "signal" },
      { t: 2400, kind: "packet", edge: "e-prompt-answer",  label: "stream",      tone: "signal", duration: 800 },
      { t: 3200, kind: "pulse",  node: "answer",           tone: "signal" },
      { t: 3200, kind: "say",    text: "Answer streamed with two cited sources" },
      { t: 3200, kind: "set",    target: "answer.text",    value: "The payment terms specify..." },
      { t: 4000, kind: "packet", edge: "e-answer-sources", label: "sources",     tone: "signal", duration: 600 },
      { t: 4600, kind: "set",    target: "sources.chips",  value: "Chunk 12, p.4 | Chunk 7, p.2" },
      { t: 4600, kind: "set",    target: "confidence",     value: "0.87 (example from the README)" },
      { t: 4600, kind: "say",    text: "Confidence 0.87 — example from the README" },
    ],
  },
];
